"""``live`` profile adapters: real SEC EDGAR grounding, generated by the Gemini API.

The live profile is the demo-facing stack: memo grounding comes from real public SEC
EDGAR records (plus any uploaded borrower documents) and the peer comparison uses real
same-SIC filed figures. Everything else reuses the SDK-free local adapters, so custody of
the index and the audit trail stays on the machine. The fictional built-in corpus never
appears under this profile.

There is deliberately no local model server. EDGAR is not Google Search, but it leaves
the data centre all the same, so this profile cannot answer without outbound network and
a laptop generator beside it would describe a deployment nobody would buy (org decision,
2026-08-30). The profile therefore needs Application Default Credentials and a
``GOOGLE_CLOUD_PROJECT``, and the UI provenance banner states that the runtime is local
while the model is Gemini.
"""
